### PR TITLE
Fix React HMR in story files

### LINKED ISSUE #3: Help wanted: React HMR is not working properly when making changes to stories

### PR DESCRIPTION
**Pull request by IanVS**
Fixes #3.

This "fixes" HMR in react story files by using the new `exclude` [option](https://github.com/vitejs/vite/pull/3916) in `@vitejs/plugin-react-refresh` to avoid treating story files as HMR boundaries, instead letting changes bubble up into the core storybook client so that it can update the manager when stories are added / deleted / changed.  When storybook detects that a story file has changed, it will trigger a reload of the preview iframe.  So, it's not exactly full seamless HMR, but it addresses the main problem of story previews not changing upon save.

To test, run `yarn install`, then `cd packages/example-react` and `yarn storybook`.  Open the button story in the browser, then make changes to the button story file (add a story, remove a story, change a story, etc).  You should see the changes reflected in the browser without requiring a manual page refresh.

### CODE REVIEW

**Comment by o-alexandrov** [comment]
Probably, also excluding `node_modules` would lead to bugs with linked dependencies which HMR should be managed by vite

File: packages/storybook-builder-vite/vite-config.js [hunk 1]
```diff
@@ -47,7 +47,10 @@ module.exports.pluginConfig = function pluginConfig(options, type) {
 
     if (type === 'development') {
         if (framework === 'react') {
-            plugins.push(require('@vitejs/plugin-react-refresh')());
+            plugins.push(require('@vitejs/plugin-react-refresh')({
+                // Do not treat story files as HMR boundaries, storybook itself needs to handle them.
+                exclude: [/\.stories\.(t|j)sx?$/, /node_modules/],
```
Comment (o-alexandrov) [inline packages/storybook-builder-vite/vite-config.js:52]: Probably, also excluding `node_modules` would lead to bugs with linked dependencies which HMR should be managed by vite

Comment (o-alexandrov) [reply packages/storybook-builder-vite/vite-config.js:52]: There should be also ability to override the exclude, as not everyone names files as `stories`

Comment (IanVS) [reply packages/storybook-builder-vite/vite-config.js:52]: >Probably, also excluding node_modules would lead to bugs with linked dependencies which HMR should be managed by vite

Excluding node_modules is the default behavior of plugin-react-refresh, so I wanted to keep that behavior for now, until/unless we hear of problems.

>There should be also ability to override the exclude, as not everyone names files as stories

There is, it is possible to change any of this config through the use of `viteFinal` in the storybook configuration file.

Comment (eirslett) [reply packages/storybook-builder-vite/vite-config.js:52]: It's also possible to read the list of stories (or the list of file globs) from the `config` variable, I think?

Comment (IanVS) [reply packages/storybook-builder-vite/vite-config.js:52]: Unfortunately it looks like `stories` from the config is not exposed to the builder. I logged out the `options` and didn't see it, and it's not in the type definitions, from what I can tell: https://github.com/storybookjs/storybook/blob/next/lib/core-common/src/types.ts#L164

Comment (eirslett) [reply packages/storybook-builder-vite/vite-config.js:52]: @shilman should that config option maybe be exposed in the builder API?

**Comment by eirslett** [comment]
I think this looks good as a first fix! It solves the 95 % use case, and the rest can be improved upon later?

File: packages/storybook-builder-vite/vite-config.js (hunk 1 above)
Comment (shilman) [reply packages/storybook-builder-vite/vite-config.js:52]: I believe you can get it from options.presets.apply('stories') but I didn't test

Comment (IanVS) [reply packages/storybook-builder-vite/vite-config.js:52]: After looking into this, it's true that we can get the `stories` as @shilman suggested.  However, those are micromatch globs, and @vitejs/react-fast-refresh uses picomatch, which does not allow brace expansion.  We would need to resolve the entire list of files and pass those to the plugin.  Since this whole approach is a bit of a bandaid, I propose that we hold off on any more complicated exclusion logic until/unless we hear of problems.  Maybe we'll find a better solution entirely that works for more than just the react framework.
