### PR TITLE
Fix: svelte

### LINKED ISSUE #224: Problem after updating from `0.1.13` to `0.1.14`. Sveltekit + Typescript + Storybook
Hi! After updating `storybook-builder-vite` version from `0.1.13` to `0.1.14` all stories disappear. 

console:
```Unexpected default export without title in './src/stories/Button.stories.svelte': undefined```

screenshot:
image

Example: https://github.com/SergeiZheleznov/sb-svelte-vite-example

The only thing changed is `storybook-builder-vite` version

### PR DESCRIPTION
**Pull request by bfanger**
1. Re-enabled the csfPlugin for svelte
2. Updated svelte dependencies, that fixed a `TypeError: RegisterContext is not a constructor` error. (Svelte compiler was in 'ssr' mode)

Fixes #224

(Also implemented support for preprocessors inside *.stories.svelte files)

### CODE REVIEW

**Comment by IanVS** [comment]
Thanks for this PR, @bfanger!  It looks like our check might need to be updated too?  

>Error: storybook-builder-vite requires @storybook/addon-svelte-csf to be installed when using @storybook/svelte.  Please install it and start storybook again.

**Comment by bfanger** [comment]
Ah, I missed adding a file in last commit. the locally compiled version of storybook-builder-vite already contained the change.

Not sure why CI fails on `@storybook/addon-svelte-csf`  running the steps from buildExamples.yml  locally (macOS) ran without error.

File: packages/storybook-builder-vite/svelte/csf-plugin.ts [hunk 1]
```diff
@@ -36,4 +42,12 @@ export default {
...
   },
+}
 };
+
+// dedent`${codeWithoutDefaultExport}
+//     const { default: parser } = require('${parser}');
+//     const __storiesMetaData = parser(${componentName}, ${JSON.stringify(storiesDef)});
+//     export default __storiesMetaData.meta;
+//     ${storyDef};
+//   `);
```
Comment (IanVS) [inline packages/storybook-builder-vite/svelte/csf-plugin.ts:53]: Just curious, why is this commented out?

**Review by IanVS — CHANGES_REQUESTED** [review]
Thanks for working on this!  When running `packages/example-svelte`, I'm seeing this error in the browser console.

```
ClientApi.js:85 Uncaught Error: Singleton client API not yet initialized, cannot call `addArgTypesEnhancer`.
```

Any idea why that might be?  

Also, I needed to add `@storybook/svelte` to the list in `optimizeDeps.ts`.  Would you mind doing that here as well?

File: packages/storybook-builder-vite/svelte/csf-plugin.ts (hunk 1 above)
Comment (bfanger) [reply packages/storybook-builder-vite/svelte/csf-plugin.ts]: I've removed  the comment, (I copied it from @storybook/addon-svelte-csf for reference, but in contrary to the error message, the export was not the issue.)

**Comment by bfanger** [comment]
Uncaught Error: Singleton client API not yet initialized, cannot call `addArgTypesEnhancer`.  
That happens when there are multiple  versions of the @storybook/client-api installed, each with its own singleton.
#50 

After a `yarn install` I run
rm -rf ./node_modules/@storybook/svelte/node_modules/@storybook/client-api
rm -rf ./node_modules/@storybook/vue3/node_modules/@storybook/client-api

to fix that issue.

I think that's a bug in yarn, it should dedupe that dependency.

**Review by IanVS — APPROVED** [review]
I was really hoping somehow this would fix that issue, but yeah, I think it's some kind of yarn bug.  

But yeah, after jumping through the hoops of removing the extra deps, this works great.  Thanks for the help!
